-- tbl_CEOPC_EMPREGADO
CREATE TABLE dbo.[tbl_CEOPC_EMPREGADO]
	(
		[ID] INT IDENTITY(1,1) NOT NULL,
		[MATRICULA] VARCHAR(7) NOT NULL PRIMARY KEY,
		[DV] CHAR NOT NULL,
		[ID_CELULA] TINYINT NULL DEFAULT 1,
		[NIVEL_ACESSO] VARCHAR(20) NULL DEFAULT 'EMPREGADO',
		[EVENTUAL_CELULA] VARCHAR(3) NULL DEFAULT 'NAO',
		[EVENTUAL_CEOPC] VARCHAR(3) NULL DEFAULT 'NAO'
	)
	ON [PRIMARY];

-- tbl_CEOPC_GRUPOS_CELULAS
CREATE TABLE dbo.[tbl_CEOPC_GRUPOS_CELULAS]
	(
		[ID] INT IDENTITY(1,1) NOT NULL,
		[NOME_CELULA] VARCHAR(20) NOT NULL PRIMARY KEY,
		[MATRICULA_GESTOR] VARCHAR(7) NOT NULL,
		[NOME_GESTOR] VARCHAR (30) NOT NULL
	)
	ON [PRIMARY];

-- tbl_ATENDIMENTO_WEB_LISTA_ATIVIDADES
CREATE TABLE dbo.[tbl_ATENDIMENTO_WEB_LISTA_ATIVIDADES]
	(
		[ID] [INT] IDENTITY(1,1) NOT NULL,
		[TIPO_GRUPO_ATENDIMENTO] [VARCHAR](20) NOT NULL,
		[NOME_ATIVIDADE] [VARCHAR](100) NOT NULL,
		[ID_CELULA] [INT] NOT NULL,
		[ATIVA] [BIT] DEFAULT 1
	) ON [PRIMARY]

-- tbl_ATENDIMENTO_WEB_REGISTRO_ATENDIMENTO
CREATE TABLE dbo.[tbl_ATENDIMENTO_WEB_REGISTRO_ATENDIMENTO]
	(
		[ID] INT IDENTITY(1,1) NOT NULL,
		[DATA_ATENDIMENTO] DATETIME NOT NULL,
		[MATRICULA_CEOPC] VARCHAR(7) NOT NULL,
		[ROTINA] BIT DEFAULT NULL,
		[CONSULTORIA] BIT DEFAULT NULL,
		[CANAL_ATENDIMENTO] VARCHAR(20) NOT NULL,
		[ITEM_LISTA_ATIVIDADES] SMALLINT NOT NULL,
		[OBSERVACAO_CEOPC] VARCHAR(2000) NULL,
		[MATRICULA_ATENDIDO] VARCHAR(7) NULL,
		[UNIDADE_DEMANDANTE] SMALLINT NOT NULL
	)
	ON [PRIMARY];

-- tbl_ATENDIMENTO_WEB_REGISTRO_PESQUISAS
CREATE TABLE dbo.[tbl_ATENDIMENTO_WEB_REGISTRO_PESQUISAS]
	(
		[ID] INT IDENTITY(1,1) NOT NULL,
		[DATA_ENVIO] DATETIME NOT NULL,
		[ID_REGISTRO_ATENDIMENTO] INT NOT NULL, -- UNIQUE
		[DATA_RESPOSTA] DATETIME NULL,
		[NOTA_CORDIALIDADE] TINYINT NULL,
		[NOTA_DOMINIO] TINYINT NULL,
		[NOTA_TEMPESTIVIDADE] TINYINT NULL,
		[FEEDBACK_ATENDIDO] VARCHAR(2000) NULL,
		[CONSULTORIA_ATENDIDA] TINYINT NULL
	)
	ON [PRIMARY];
