USE [DB5624_GEOPC_COMPLEMEX]
GO
/****** Object:  StoredProcedure [dbo].[sp_relatorio_atendimento_web_middle]    Script Date: 10/01/2019 12:28:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[sp_relatorio_atendimento_web_middle]
AS

IF OBJECT_ID('[dbo].[tbl_ATENDIMENTO_WEB_RELATORIO_INDICADORES]') IS NOT NULL
DROP TABLE [dbo].[tbl_ATENDIMENTO_WEB_RELATORIO_INDICADORES]

CREATE TABLE [dbo].[tbl_ATENDIMENTO_WEB_RELATORIO_INDICADORES]
(
[MES] VARCHAR(7) NULL,
[RS] INT NULL,
[SC] INT NULL,
[MT] INT NULL,
[MS] INT NULL,
[PR] INT NULL,
[SP] INT NULL,
[DF] INT NULL,
[MG] INT NULL,
[ES] INT NULL,
[RJ] INT NULL,
[AM] INT NULL,
[RR] INT NULL,
[AP] INT NULL,
[PA] INT NULL,
[TO] INT NULL,
[RO] INT NULL,
[AC] INT NULL,
[GO] INT NULL,
[MA] INT NULL,
[PI] INT NULL,
[CE] INT NULL,
[RN] INT NULL,
[PB] INT NULL,
[PE] INT NULL,
[AL] INT NULL,
[SE] INT NULL,
[BA] INT NULL,
[UF_OUTROS] INT NULL,
[DIRE_A] INT NULL,
[DIRE_B] INT NULL,
[DIRE_C_D] INT NULL,
[DIRE_E] INT NULL,
[DIRE_F] INT NULL,
[DIRE_G] INT NULL,
[DIRE_H] INT NULL,
[DIRE_OUTROS] INT NULL,
[TOTAL] INT NULL,
);

DECLARE @MES AS INT
DECLARE @ANO AS INT
DECLARE @CONTADOR AS INT

--SET @ANO = YEAR(GETDATE())
--SET @MES = MONTH(GETDATE())-2

SET @ANO = YEAR(GETDATE())
SET @MES = MONTH(GETDATE())

SET @CONTADOR = 1

IF @MES = 1
BEGIN
	SET @MES = 11
	SET @ANO = @ANO - 1
END
	ELSE IF @MES = 2
	BEGIN
		SET @MES = 12
		SET @ANO = @ANO - 1
	END


WHILE @ANO <=  2019
BEGIN
	WHILE @CONTADOR <= 3
	BEGIN
		--SELECT 'MÊS' = @MES, 'ANO' = @ANO, 'CONTADOR' = @CONTADOR
		WITH CONTAGEM_UF AS
		(
			SELECT 
				DISTINCT ATENDIMENTO.[ID]
				,DATA_ATENDIMENTO
				,'MES' = CONCAT(YEAR(ATENDIMENTO.[DATA_ATENDIMENTO]), '/', MONTH(ATENDIMENTO.[DATA_ATENDIMENTO])) 
				,'UF' = CASE 
							WHEN UNIDADES.[UF] IS NOT NULL THEN UNIDADES.[UF]
							ELSE 'OUTROS'
						END
				,'DIRE' = CASE
							WHEN UNIDADES.[UF] IN ('RS', 'SC') THEN	'DIRE A'
							WHEN UNIDADES.[UF] IN ('MT', 'MS', 'PR') THEN	'DIRE B'
							WHEN UNIDADES.[UF] IN ('SP') THEN	'DIRE C e D'
							WHEN UNIDADES.[UF] IN ('DF', 'MG') THEN	'DIRE E'
							WHEN UNIDADES.[UF] IN ('ES', 'RJ') THEN	'DIRE F'
							WHEN UNIDADES.[UF] IN ('AM', 'RR', 'AP', 'PA', 'TO', 'RO', 'AC', 'GO') THEN	'DIRE G'
							WHEN UNIDADES.[UF] IN ('MA', 'PI', 'CE', 'RN', 'PB', 'PE', 'AL', 'SE', 'BA')  THEN	'DIRE H'
							ELSE 'OUTROS'
						END
			FROM 
				[tbl_ATENDIMENTO_WEB_REGISTRO_ATENDIMENTO] AS ATENDIMENTO
				LEFT JOIN [tbl_UNIDADES_DIRE] AS UNIDADES ON 
				ATENDIMENTO.[UNIDADE_DEMANDANTE] = UNIDADES.[CD_AG]
				OR ATENDIMENTO.[UNIDADE_DEMANDANTE] = UNIDADES.[CD_SR]
			WHERE 
				MONTH(ATENDIMENTO.[DATA_ATENDIMENTO]) = @MES
		)
		
		INSERT INTO [dbo].[tbl_ATENDIMENTO_WEB_RELATORIO_INDICADORES] ([MES], [RS], [SC], [MT], [MS], [PR], [SP], [DF], [MG], [ES], [RJ], [AM], [RR], [AP], [PA], [TO], [RO], [AC], [GO], [MA], [PI], [CE], [RN], [PB], [PE], [AL], [SE], [BA], [UF_OUTROS], [DIRE_A], [DIRE_B], [DIRE_C_D], [DIRE_E], [DIRE_F], [DIRE_G], [DIRE_H], [DIRE_OUTROS], [TOTAL])
		
		SELECT DISTINCT
			'MES' = CONCAT(YEAR([DATA_ATENDIMENTO]), '/', MONTH([DATA_ATENDIMENTO])) 
			,'RS' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'RS' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'SC' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'SC' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'MT' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'MT' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'MS' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'MS' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'PR' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'PR' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'SP' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'SP' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DF' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'DF' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'MG' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'MG' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'ES' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'ES' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'RJ' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'RJ' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'AM' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'AM' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'RR' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'RR' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'AP' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'AP' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'PA' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'PA' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'TO' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'TO' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'RO' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'RO' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'AC' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'AC' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'GO' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'GO' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'MA' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'MA' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'PI' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'PI' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'CE' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'CE' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'RN' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'RN' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'PB' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'PB' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'PE' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'PE' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'AL' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'AL' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'SE' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'SE' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'BA' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'BA' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'UF_OUTROS' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE UF = 'OUTROS' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DIRE A' = (SELECT COUNT(DIRE) FROM CONTAGEM_UF WHERE DIRE = 'DIRE A' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DIRE B' = (SELECT COUNT(DIRE) FROM CONTAGEM_UF WHERE DIRE = 'DIRE B' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DIRE C e D' = (SELECT COUNT(DIRE) FROM CONTAGEM_UF WHERE DIRE = 'DIRE C e D' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DIRE E' = (SELECT COUNT(DIRE) FROM CONTAGEM_UF WHERE DIRE = 'DIRE E' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DIRE F' = (SELECT COUNT(DIRE) FROM CONTAGEM_UF WHERE DIRE = 'DIRE F' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DIRE G' = (SELECT COUNT(DIRE) FROM CONTAGEM_UF WHERE DIRE = 'DIRE G' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DIRE H' = (SELECT COUNT(DIRE) FROM CONTAGEM_UF WHERE DIRE = 'DIRE H' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'DIRE_OUTROS' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE DIRE = 'OUTROS' AND MONTH(DATA_ATENDIMENTO) = @MES)
			,'TOTAL' = (SELECT COUNT(UF) FROM CONTAGEM_UF WHERE MONTH(DATA_ATENDIMENTO) = @MES)
		FROM 
			CONTAGEM_UF
		SET @MES = @MES + 1
		SET @CONTADOR = @CONTADOR + 1
		IF @CONTADOR = 4
		BEGIN
			SET @ANO = YEAR(GETDATE()) + 1
		END
		IF @MES = 13
		BEGIN
			SET @MES = 1
		END
	END
	SET @ANO = @ANO + 1
END