DECLARE @MES_ANTERIOR AS INT
DECLARE @EMPREGADOS AS INT

				DECLARE @PERIODO_INICIAL AS DATETIME

				

				SET @MES_ANTERIOR = DATEPART(MONTH, DATEADD(MONTH, -2, GETDATE()))

				SET @PERIODO_INICIAL = CASE @MES_ANTERIOR 
											WHEN 10 THEN CONVERT(DATETIME, CONCAT(DATEPART(YEAR, DATEADD(YEAR, -1, GETDATE())), '-', RIGHT('0' + RTRIM(DATEPART(MONTH, DATEADD(MONTH, -3, GETDATE()))), 2), '-', '01', ' ', '00:00:00'), 120)
											WHEN 11 THEN CONVERT(DATETIME, CONCAT(DATEPART(YEAR, DATEADD(YEAR, -1, GETDATE())), '-', RIGHT('0' + RTRIM(DATEPART(MONTH, DATEADD(MONTH, -2, GETDATE()))), 2), '-', '01', ' ', '00:00:00'), 120)
											WHEN 12 THEN CONVERT(DATETIME, CONCAT(DATEPART(YEAR, DATEADD(YEAR, -1, GETDATE())), '-', RIGHT('0' + RTRIM(DATEPART(MONTH, DATEADD(MONTH, -1, GETDATE()))), 2), '-', '01', ' ', '00:00:00'), 120)
											ELSE GETDATE()
										END

				-- QUANTIDADE DE EMPREGADOS QUE REALIZARAM REGISTROS NO MÊS ATUAL
				SET @EMPREGADOS = (SELECT COUNT(DISTINCT EMPREGADOS.[MATRICULA]) FROM 
					[tbl_ATENDIMENTO_WEB_REGISTRO_ATENDIMENTO] AS ATENDIMENTO 
					INNER JOIN [EMPREGADOS] ON CONVERT(BIGINT,REPLACE(ATENDIMENTO.MATRICULA_CEOPC, 'c', '')) = EMPREGADOS.[MATRICULA]
					WHERE [DATA_ATENDIMENTO] >= CONVERT(DATETIME, CONCAT(DATEPART(YEAR, DATEADD(YEAR, 0, GETDATE())), '-', RIGHT('0' + RTRIM(DATEPART(MONTH, DATEADD(MONTH, 0, GETDATE()))), 2), '-', '01', ' ', '00:00:00'), 120))

				SELECT 
				    'lote' = CONCAT(DATEPART(YEAR,[DATA_ATENDIMENTO]),'/', RIGHT('0' + RTRIM(DATEPART(MONTH,[DATA_ATENDIMENTO])), 2))
					,'nome' = 'MIDDLE OFFICE'
				    ,'mediaRotina' = COUNT(ATENDIMENTO.[ROTINA]) / @EMPREGADOS
					,'mediaConsultoria' = COUNT(ATENDIMENTO.[CONSULTORIA]) / @EMPREGADOS
					,'mediaTotalAtendimentos' = (COUNT(ATENDIMENTO.[ROTINA]) / @EMPREGADOS) + (COUNT(ATENDIMENTO.[CONSULTORIA]) / @EMPREGADOS)
				FROM 
					[tbl_ATENDIMENTO_WEB_REGISTRO_ATENDIMENTO] AS ATENDIMENTO 
					INNER JOIN [EMPREGADOS] ON CONVERT(BIGINT,REPLACE(ATENDIMENTO.MATRICULA_CEOPC, 'c', '')) = EMPREGADOS.[MATRICULA]
				WHERE 
					-- Filtro para retornar os últimos três meses
					[DATA_ATENDIMENTO] >= @PERIODO_INICIAL
				GROUP BY 
					CONCAT(DATEPART(YEAR,[DATA_ATENDIMENTO]),'/', RIGHT('0' + RTRIM(DATEPART(MONTH,[DATA_ATENDIMENTO])), 2))
				ORDER BY 
					LOTE DESC